### ISSUE TITLE
[Data Layers] Item Overlay

### ISSUE THREAD

**Issue by 42willow** [Pathoschild/LookupAnything#1013]
It would be nice to have an overlay for different item categories, to help with organising your chests/storage.

I'd be happy to help with this, I am just opening an issue to see if the idea is feasible. 

There could also be overlays for if seeds/fish are in season etc. (or that could be something for the Lookup Anything mod

**Comment by Pathoschild** [comment]
Hi! Data Layers is only set up for world overlays currently (rather than menu overlays), but I'm happy to discuss the idea if you're interested in contributing a feature for it.

I don't use GitHub issues for suggestions though, so I'll close this ticket. Could you come ping me in [#making-mods on the Stardew Valley Discord](https://smapi.io/community#Discord) if you want to discuss further?
