### ISSUE TITLE
[Automate]: Coal from charcoal kiln not deposited into chest

### ISSUE THREAD

**Issue by annahansen229** [Pathoschild/LookupAnything#1062]
**Describe the bug**
The coal produced by the charcoal kiln is missing from the chest. The wood is fed into the kiln, and the animation shows the coal has been produced, but the coal does not show up in the chest. The kilns consume all the wood and deposit no coal.

**To Reproduce**
1. Place chest next to charcoal kiln
2. Deposit wood in chest
3. Watch kiln consume wood and produce coal
4. Open chest and find no coal

**Log file**
https://smapi.io/log/3d22318b0b954b9dadccb92a4b4525e7

**Screenshots**

**Comment by Pathoschild** [comment]
Hi! That's usually because the machine is connected to another chest or machine that's taking the output. You can press `U` in-game to see an overlay which highlights what each machine is connected to.

Note that these GitHub issues are only used to track planned technical work, so you won't get a quick response here. Feel free to ask on the mod page instead for support questions like this.

**Comment by annahansen229** [comment]
Hi! The chest wasn't connected to any other machine, it was just the
machine and one chest connected to each other. No paths connecting them
either. It was odd, only happened with this machine. No problems with any
other machine.

**Comment by Pathoschild** [comment]
Can you come ask on [Automate's mod page](https://www.nexusmods.com/stardewvalley/mods/1063) so I can help there? (You can link to this page for context, and so we can update it when we find the issue.)
