### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by HyperionHeli** [Pathoschild/LookupAnything#1066]
**Describe the bug**
Putting a chest or a mini fridge next to a machine that I supposed to only produce once a day (coffee machine, statue of perfection) causes it to keep producing items as soon as they have been moved to the chest next to it, causing thousands of items to pile up. This can also be reproduced by grabbing the coffee/iridium by hand while a chest is next to it. This is an issue in a multiplayer game.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Load save in multiplayer!
2. Place a chest/minifridge next to a coffee machine or statue of perfection
3. Take an item from the machine and look in the chest, it will constantly reproduce the item.
4. Item gets duplicated infinitely 

I am not fully sure if the big occured after putting the mini fridge next to the coffee machine but restarting the game did not fix it.

**Comment by Pathoschild** [comment]
Hi! That's probably due to another player having a mod like CJB Cheats Menu which enables fast machine processing. Can you come ask on the CJB Cheats Menu page or [on Discord](https://smapi.io/community#Discord) so we can help you look into it?

I'll close this though, since these GitHub issues are only used to track planned technical work rather than support questions.
