### ISSUE TITLE
[Content Patcher] 1.3 alpha: some changes not applied in Starblue Valley

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/LookupAnything#209]
Some changes in Starblue Valley alpha aren't applied in Content Parcher 1.3 alpha.

See:
* [content pack](https://cdn.discordapp.com/attachments/156109690059751424/425531674873561088/StarblueValley.7z)
* [verbose log](https://log.smapi.io/gFc8YcwF) (failing entries have `BAD!` in the name).

**Comment by Pathoschild** [comment]
Also this (patch: `sprobj: stick debris`):
> ![image](https://user-images.githubusercontent.com/230581/37638829-3909766a-2be5-11e8-8564-fa620d8599e4.png)

**Comment by jcgarvey** [comment]
I put together a new content.json that supported some additional variations I wished to offer (support for magimatica's Hudson Valley chickenhouse for Shane and a blue spruce colorway for the pine tree). It dramatically increased the number of patches I had to do for each {{season}}_outdoorsTileSheet. When I tried it in game, almost nothing loaded. Is it possible that the system isn't handling the large number of edits well? I've attached the new content.json for your convenience.
[bigcontent.zip](https://github.com/Pathoschild/StardewMods/files/1828478/bigcontent.zip)

**Comment by strangelyliteral** [comment]
Reposted due to wrong account. I put together a new content.json that supported some additional variations I wished to offer (support for magimatica's Hudson Valley chickenhouse for Shane and a blue spruce colorway for the pine tree). It dramatically increased the number of patches I had to do for each {{season}}_outdoorsTileSheet. When I tried it in game, almost nothing loaded. Is it possible that the system isn't handling the large number of edits well? I've attached the new content.json for your convenience.
[bigcontent.zip](https://github.com/Pathoschild/StardewMods/files/1828493/bigcontent.zip)

**Comment by Pathoschild** [comment]
## Issue 1 and 3: some changes aren't applied
This happens when we change a texture after the game has started using it. SMAPI has logic to update references to it, but it doesn't cover all core assets yet. I created pathoschild/SMAPI#459 to address that in 2.5.4 before Content Patcher 1.3 is released. I'll keep this open until the 2.5.4 beta is available.

## Issue 2: red overlay over sticks
That's normal. The patch is overlaying `{ "X": 96, "Y": 192, "Width": 32, "Height": 16 }` from `assets/Cursors.{{language}}.png`, which looks like this:
> ![](https://user-images.githubusercontent.com/230581/37687661-d315d266-2c72-11e8-881b-b06c55e90716.png)

**Comment by Pathoschild** [comment]
Followup: issue 1 was because the content pack mistakenly targeted `spring_outdoorsTileSheet` twice and left out `Maps/spring_outdoorsTileSheet`.

**Comment by Pathoschild** [comment]
Should be fixed in the next Content Patcher beta build.
