### ISSUE TITLE
[Data Map] Lag with Accessibility Map

### ISSUE THREAD

**Issue by RuiNtD** [Pathoschild/LookupAnything#264]
As I have suggested to Pathoschild, this could be solved by:
1. Decreasing how often calculations occur.
2. Updating in chunks.
3. Update asynchronously.

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming Data Maps 1.4-beta.3.

Each data map now updates at a more nuanced rate (instead of the previous 60 updates/second) based on two per-map settings:
* `UpdatesPerSecond`: how often the map should update. The maximum is 60/second, but can be less than one to update less than once per second (or zero to disable the data map entirely).
* `UpdateWhenViewChange`: Whether to update when your viewpoint in the game changes, regardless of the `UpdatesPerSecond` value.

Here are the default settings:

map | updates/second | update when view changes
--- | -------------- | ------------------------
Accessibility | 2 | true
Bee houses | 60 | true
Junimo huts | 60 | true
Scarecrows | 60 | true
Sprinklers | 60 | true
Crop fertiliser | 30 | true
Crop water | 30 | true
