### ISSUE TITLE
[Chests Anywhere] Compatiility with Mega Storage (Mega Storage chests show as vanilla chests)

### ISSUE THREAD

**Issue by klaurence** [Pathoschild/LookupAnything#434]
Simply, the chests from Mega Storage, _which as intended should show as 12x6 (and if it's a Magic Chest, should be scrollable and should show go down/go up buttons on the right side)_, doesn't always do so with Chests Anywhere.

I've noticed a few things relating to the compatibility between Chests Anywhere and Mega Storage:

- When opening a Mega Storage chest, the MS chests show as intended. The UI elements of Chests Anywhere _(chest icon, "Categorize", "Stash", name of chest field, "message"/customize button, location field, "Toggle Color Picker", organize buttons)_ also show.
- When navigating between chests though, the MS chests show as a vanilla chest _(12x3, isn't scrollable, has no vertical navigation buttons on the side)_. The UI elements show.

**Comment by Pathoschild** [comment]
That's something Mega Storage would need to support. Chests Anywhere automatically adjusts for the custom menu (which is why it works when you open the chests directly), but it can't open the expanded chest menu itself. Mega Storage would need to detect when a normal chest menu is opened, and reopen it through its custom UI.

**Comment by klaurence** [comment]
The creator of the Mega Storage mod has fixed this problem for v1.0.9.
