### ISSUE TITLE
[Tractor Mod] This mod is disabled because the host player doesn't have it installed.

### ISSUE THREAD

**Issue by AshaSalorina** [Pathoschild/LookupAnything#528]
All of our players were installed tractor but this error still happend. I tried this in 4.10

**Comment by Pathoschild** [comment]
Can you try it again, upload the logs for the main player and one of the farmhands getting the error to [smapi.io/log](https://smapi.io/log/), and post the links here?

**Comment by AshaSalorina** [comment]
Thanks.
Here is the main player's log: https://smapi.io/log/7d685474da43477db0a79ec382abb763
And this log for farmhand: https://smapi.io/log/cdb3f4153d554d7a948b80bf20dc526e

**Comment by Pathoschild** [comment]
The host isn't sending the SMAPI info:
> [21:49:17] Received connection for vanilla host 4933385446648006509.

I see you're running a SMAPI fork for WeGame compatibility, and the log mentions a 'Rail SDK' which I assume is the multiplayer client for WeGame. It seems the WeGame fork isn't handling multiplayer correctly; I suggest asking the fork author about that.

I'll close this since it's not an issue with Tractor Mod, but I'll look into what would be needed for the main SMAPI to be compatible with WeGame. Thanks for reporting it!
