### ISSUE TITLE
[Content Patcher] Load other types of patches from files

### ISSUE THREAD

**Issue by minervamaga** [Pathoschild/LookupAnything#557]
Currently only `EditData` supports loading from a file.  For some complex image patches, you can end up with a thousands of lines json file that can be difficult to navigate when troubleshooting.  Unsure if it's possible, but allowing other types of patches to load from a separate json would help with navigation greatly.  Perhaps set the type of edit for all of the blocks in the json and just have log name, target, from file, and conditions in the second json.  Being able to split the coding work would help collaborative teams as well.

**Comment by Pathoschild** [comment]
That `FromFile` option loads the content for the patch type (e.g. the data for `EditData`, the image for `EditImage`, the asset for `Load`, etc). We couldn't repurpose it directly without breaking how it's used, so we'd need some new field or mechanism. Maybe something like this:

```js
{
   "Action": "LoadPatches",
   "FromFile": "some-patches.json",
   "When": { ... }
}
```

That would imply some major changes to how Content Patcher works though, since it couldn't parse/analyse patches ahead of time anymore. I don't have any timeline for when (or if) I'll add a feature for this, but I'll keep this open as a tracking ticket in the meantime.

**Comment by Pathoschild** [comment]
Added in Content Patcher 1.16 using the new `"Action": "Include"` patch type.

**Comment by minervamaga** [comment]
*blinks*  Wasn't expecting that!
