### ISSUE TITLE
[Automate]Compatibility question with [ChestEX] Mod 

### ISSUE THREAD

**Issue by DL0101** [Pathoschild/LookupAnything#568]
I'm not sure if this is an issue with ChestEX or Automate.When these two mods are used together, Automate seems to be able to detect only a limited number of cells in the box, as if only the size of the original box, and can not detect the part I added through Chestex.

**Comment by Pathoschild** [comment]
Hi! Automate should see all items in the chest, but when pushing new items into the chest it depends on the max size specified in the chest data. [Mods can override that](https://github.com/Pathoschild/StardewMods/blob/develop/Automate/technical.md#custom-chest-capacity), so that would be a question for the ChestEx author.
