### ISSUE TITLE
[Data Layers] (Feature Request) Display NPC/Villager Pathing Tiles

### ISSUE THREAD

**Issue by Zefferis** [Pathoschild/LookupAnything#585]
I learned recently that craftables like chests can be placed outside of the farm, but I also saw some images of 1.4 NPC Pathing which if blocked, villagers destroy the crafted item to continue their path

It would be a pretty helpful if within Data Layers, players can see which tiles are pathed by a villagers (or valid for craftable placement without being destroyed by a NPC)

Thanks!

**Comment by Pathoschild** [comment]
Thanks for the suggestion! Unfortunately NPC pathing is dynamic based on their current position and schedules, so there isn't really any way to display it in a layer. The path maps in 1.4 were generated by keeping track of all the tiles NPC walked at least once over a certain period of time. I'll close this ticket since it doesn't seem feasible, but pull requests are welcome if someone figures out a way to do it.

You might like [Non Destructive NPCs](https://www.nexusmods.com/stardewvalley/mods/5176) though.
