### ISSUE TITLE
[Data Layers] Animal Overlay

### ISSUE THREAD

**Issue by minervamaga** [Pathoschild/LookupAnything#608]
Baby animals can be very hard to see in tall grass or behind other objects.  Some type of overlay that allows you to view animals would be a huge help for this.  For other data on that layer, possibly accessible grass/water tiles and the location of the barn/coop doors?  Possibly truffle spawning spots available as well.

**Comment by Pathoschild** [comment]
Thanks for the suggestion! I'll have to think about some way to make this intuitive and generic enough; this might also be worth a separate mod that makes animals easier to see or adds an indicator when they're in tall grass. I'll close this ticket in the meantime though, since I don't track ideas on GitHub.
