### ISSUE TITLE
[Chests Anywhere] rework chest config menu

### ISSUE THREAD

**Issue by firereverie** [Pathoschild/LookupAnything#633]
Replace the chest config button and menu page with a third dropdown menu (similar to how categories and chest selection works now) with selections for the existing config options.

This also happens to fix the android issues I posted about on nexus with the config screen not drawing properly as well as the issue of the config button not rendering on android.

**Comment by Pathoschild** [comment]
Thanks for the suggestion! Unfortunately that doesn't really work with most of the options, since they're not toggles. You wouldn't be able to have textboxes in a dropdown for example. There's no reason the option menu page wouldn't work on Android, it just needs an Android mod developer to see why it doesn't work and fix that.
