### ISSUE TITLE
[Tractor Mod] CP expanded upgrade paths

### ISSUE THREAD

**Issue by firereverie** [Pathoschild/LookupAnything#634]
Expose the ability to add upgrade levels to the tractor in Robin's build menu with their own discrete tool options and tags (for things like different audio and assets for different tractors).

Would allow for different tractors for different functions, specialty tractors designed around custom tools, upgrade path story lines with events ect.

Basically turns tractor mod into tractor framework...

**Comment by Pathoschild** [comment]
Thanks for the suggestion! That would be interesting to look into, but unfortunately most of my time goes towards SMAPI/Content Patcher and supporting the modding community, so I'm not sure when I'd be able to dedicate that much time to one mod. I'll close this ticket since I don't track suggestions through GitHub issues though.
