### ISSUE TITLE
[Tractor Mod] allow keybindings for increasing and decreasing tractor range & speed

### ISSUE THREAD

**Issue by etmoonshade** [Pathoschild/LookupAnything#638]
What it says on the tin.

Use case is that sometimes I want the tractor to cover a wide area (gathering crops, for example) and other times I want it to cover a smaller area (tilling dirt for a line of crops.)

Similarly, I like a high tractor speed when moving from point to point, but bump the speed down when I'm tilling/planting/etc. because I've seen it skip if the speed is too high.

Obviously I'm able to use the mod config menu to change it on the fly so it's not a super urgent request - just QoL.

**Comment by Pathoschild** [comment]
Thanks for the suggestion! You can change the range/speed through the in-game options menu using [Generic Mod Config Menu](https://www.nexusmods.com/stardewvalley/mods/5098) though like you mentioned, so I don't have any plans to add keybinds to edit individual options (since the configuration is pretty complex already).
