### ISSUE TITLE
[Content Patcher] & [Json Assets] 

### ISSUE THREAD

**Issue by Logandoidao** [Pathoschild/LookupAnything#641]
I need to know how to add buffs to the weapons I'm adding with mod 
It would be possible to do this with only one file .Json? 
I do my mods on the phone, it would be great to do this only with lines of code in a file .Json

Creating the arts on mobile is a difficult task 
I'm limited to what I can do using only Android-compatible programs

**Comment by Pathoschild** [comment]
Hi! Unfortunately you can't edit player buffs with Content Patcher, since they're defined in the game code (rather than the content assets). You can change weapon stats with both Content Patcher and Json Assets, but for players buffs you'll need to [create a SMAPI mod](https://stardewvalleywiki.com/Modding:Modder_Guide).
