### ISSUE TITLE
[Lookup Anything] Do not show recipes until acquiring them

### ISSUE THREAD

**Issue by Deflaktor** [Pathoschild/LookupAnything#655]
So yeah, would be nice if ProgressionMode also hid recipes which havent been acquired yet.

**Comment by b3nk3lly** [comment]
I know this is an old one but I'd also like to see this. I have a proof of concept version here: https://github.com/b3nk3lly/StardewMods/tree/lookup-anything/hide-unknown-recipes

I have the "Needed for" section showing a count of unknown recipes, similar to how its done for gifting. Also I removed unknown crafting recipes from the "Recipes" section.

Is this something people are interested in ? I'm happy to submit a PR for it. I would need help with translations if possible.

<img width="669" alt="hidden-unknown-recipes" src="https://github.com/Pathoschild/StardewMods/assets/76674774/d43c3a02-99d6-46bb-8273-e370c1cd6728">

**Comment by Pathoschild** [comment]
Sure, PRs are welcome! Ideally the 'Recipes' field should show that there's hidden recipes too (similar to gift taste fields), but otherwise that looks good.

You don't really need to worry about translations (aside from trying to minimize the number of new translations). They'll just show the English text temporarily until we get the new translations.

**Comment by Pathoschild** [comment]
Added by @b3nk3lly via #939 for the upcoming Lookup Anything 1.43.0. Thanks for the help!
