### ISSUE TITLE
[BUG] Gather Quests 

### ISSUE THREAD

**Issue by TheExceed** [Pathoschild/LookupAnything#664]
Hello, recently had a gather quest for gathering 12 potato juice from kegs well I set it up to be automatic with this mod and I made 6 kegs so 2 crafts worth however it claims I only "Gathered" 10/12 even though there are indeed 12 in the stack. I assume its because I am not actually gathering them from kegs.

**Comment by Pathoschild** [comment]
Hi! Gather quests count items you pick up that were never in a player inventory. They don't actually need to be from kegs (e.g. spawning items works too). Automate has no effect on the count, since the game will count the items when you pick them up from the chests. So that sounds like a game bug, which you can [report in the official forums](https://forums.stardewvalley.net/forums/help-bug-reports-non-modded.12/) if you're able to reproduce it without mods.
