### ISSUE TITLE
[Tractor Mod] Distance

### ISSUE THREAD

**Issue by jdroo** [Pathoschild/LookupAnything#666]
This is more of a request/new feature, could you make it so you could set a distance braced on what tool used? So you can set them each individually?

I noticed the Hoe when max distance is up lags so bad , yet most other tools are nowhere as bad, I think if you made it so each tool could have it's own distance setting, it would make it a lot more optimized,  Also giving the Magnet it's own distance would be nice too.

Just think if these were settings, it would make it lots more easy to use, and a lot more lag friendly.

Another Idea is make it so you can use any weapon/tool to kill monsters, I noticed the hoe can kill mobs, but the issue with that is that's the one that causes continuous lag, can you make it so all tools, the hoe, picaxe, axe, and scythe can do damage by default?

Another Idea is to make it so when planting seeds/ spreading fertilizer, that if you use up all of one bag of it it auto swaps to the next available bag?

any-who, just a few small improvement ideas. sorry for the bother!

**Comment by Pathoschild** [comment]
Thanks for the suggestions! I'll close this ticket since I only use GitHub issues to track specific planned dev tasks, but I'll address them below instead.

* The magnetic distance is already configurable using the `MagneticRadius` option. The magnetism doesn't have a strict distance (since its strength just tapers off with distance), but higher values = further distance.

* I could look into adding per-tool distance if it's something many players request. I have ideas to make the mod much more configurable in future versions (e.g. to enable any feature for any tool); if that happens, I could possibly make the distance configurable per-tool at the same time.

* The hoe performance is due to the way it's implemented currently. Unlike other tools which pre-check each tile to see if they need to be applied, the hoe is just applied to every surrounding tile once per tractor tool update. That could certainly be optimized in future versions to support players with a large distance value.

* Using the hoe to kill monsters is a quirk of the way it's implemented (see above). Using any tool to attack monsters would be part of the config revamp I mentioned earlier, but in the meantime you can enable weapons instead.

* I think sowing seeds from multiple bags might be a feature of [Seed Bag](https://www.nexusmods.com/stardewvalley/mods/1133) (and Tractor Mod is preconfigured to support it). That mod is broken right now, but it'll probably be updated at some point when the author is less busy.
