### ISSUE TITLE
[Content Patcher] Map update issues for farmhands

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/LookupAnything#730]
In multiplayer, maps don't update correctly for farmhands in some cases. Common symptom include conditional changes not applied or unapplied, or corrupted community center textures (see examples [one](https://user-images.githubusercontent.com/230581/171780939-b8425912-4fa8-41d1-a8d6-e7416d969344.png) and [two](https://user-images.githubusercontent.com/230581/171780979-c2b6c057-3262-4143-afc4-b74ce53b7a07.png)).

Reported by `mcms1900#5599` and `SinZ#0403` on the Stardew Valley Discord.

## Repro steps
1. Install [this `Mods` folder](https://github.com/Pathoschild/StardewMods/files/8829337/Mods.zip).
2. Load a new save.
3. Change the date to Friday.
4. Get a farmhand to connect.
5. Sleep in-game.
6. Go to town and make sure the Market Day content is correctly shown for both host and farmhand.
7. Sleep in-game.
8. Go to town.

**Expected result:** the Market Day stalls should be gone for both host + farmhand.

**Actual result:** the farmhand [still sees the empty stalls](https://user-images.githubusercontent.com/230581/171781298-5fac3a56-067d-4339-90b5-7a391977c149.png).

**Comment by brucethemoose** [comment]
Here are the logs from that above scenario: 

Host: https://smapi.io/log/fd36daf80ab4470abb47b4c0bcd1a721

Client: https://smapi.io/log/fd36daf80ab4470abb47b4c0bcd1a721

I documented this issue with more screenshots, albeit in a less minimal environment and with some unrelated MP issues, here: https://github.com/ceruleandeep/CeruleanStardewMods/issues/5


I'll see if I can get another minimal mod/save zip from something else like SVE, where this issue is very common.

**Comment by Pathoschild** [comment]
[Fixed in the upcoming SMAPI 3.18.0](https://github.com/Pathoschild/SMAPI/pull/883), thanks to @SinZ163!
