### ISSUE TITLE
[ CP ] and [ CP - A ] Yesterday's Weather

### ISSUE THREAD

**Issue by StrangePanda0** [Pathoschild/LookupAnything#768]
can you help me to get yesterday's weather? in numerical, cuze i tried Query Token but it didn't work even directly in Changes > When or DynamicToken > When and DynamicToken > Value, well if i use Random, it'll work but not based on yesterday's weather, can somebody help me? this for my mod wich also uses Content Patcher Animations, here's my code.

{
"Format": "1.19.0",
"ConfigSchema": {
"1.5": {
"AllowValues": "true, false",
"Default": "false"
}
},
"DynamicTokens": [
{
"Name": "Date_Of_Storm",
"Value": "{{query: {{Day}} + 1}}",
"When": {
"Weather": "Storm",
"Day": "{{Range: 1, 27}}"
}
},
{
"Name": "Date_Of_Storm",
"Value": "1",
"When": {
"Weather": "Storm",
"Day": "28"
}
},
{
"Name": "Weathers",
"Value": "New_Sun_Wet",
"When": {
"Weather": "Sun",
"Day": "{{Date_Of_Storm}}"
}
},
{
"Name": "Weathers",
"Value": "New_Wind_Wet",
"When": {
"Weather": "Wind",
"Day": "{{Date_Of_Storm}}"
}
}
],
"Changes": [
{
"LogName": "Animation 0001",
"Action": "EditImage",
"Target": "Maps/{{Season}}_outdoorsTileSheet",
"FromFile": "Assets/Environment/{{Weathers}}/{{Season}}_01.png",
"FromArea": {
"X": 0,
"Y": 0,
"Width": 16,
"Height": 176
},
"ToArea": {
"X": 0,
"Y": 96,
"Width": 16,
"Height": 176
},
"AnimationFrameCount": 16,
"AnimationFrameTime": 10
}
]
}

**Comment by Pathoschild** [comment]
Hi! You can't get the previous day's weather through Content Patcher's default tokens.

Other mods can add custom tokens for things like this though. I suggest asking in [#making-mods on the Stardew Valley Discord](https://smapi.io/community#Discord); a lot more mod authors will see your question there, since the GitHub issues are only used to track development tasks.
