### ISSUE TITLE
[Tractor Mod] Mushroom tree saplings

### ISSUE THREAD

**Issue by nanypoco** [Pathoschild/LookupAnything#791]
Mushroom tree saplings are cut by Axe Features even when "CutTreeStumps": true and "ClearTreeSaplings": false.

**Comment by Pathoschild** [comment]
Hi! I can't reproduce that in the current build (see screenshots of [the mod config](https://github.com/Pathoschild/StardewMods/assets/230581/ad4e5306-958a-4ef3-af49-be2e3cb29ceb) and the [tractor not chopping mushroom saplings](https://github.com/Pathoschild/StardewMods/assets/230581/ace31700-9b70-4735-a28c-4c1342c05db6)). I'll close this ticket since I don't track questions/support on GitHub, but feel free to comment on [the Tractor Mod page](https://www.nexusmods.com/stardewvalley/mods/1401) if you're still having the issue.
