### ISSUE TITLE
[Look up anything] EXP bars filling in beyond the current level

### ISSUE THREAD

**Issue by Pet-Slime** [Pathoschild/LookupAnything#794]
A cosmetic change yeah, but it would be nice if exp bars only filled in up to the current level. Currently they fill in the exp of each bar.

**Comment by Pathoschild** [comment]
Hi! The current design is meant to show progress towards each level. For example, if you have 90% of the XP needed for level one and 50% of the XP for level 2, it'll show the first two bars at 90% and 50% full respectively.

I can certainly change that if players find it confusing though; could you add a comment on the [Lookup Anything mod page](https://www.nexusmods.com/stardewvalley/mods/541) to see what other players think? I'll close this ticket since I don't track questions/suggests on GitHub, but feel free to comment there if you'd like to discuss further!
