### ISSUE TITLE
[Chests Anywhere] feature: Chests as read-only

### ISSUE THREAD

**Issue by arphox** [Pathoschild/LookupAnything#795]
Hi!

I have been looking for a mod which makes it possible to label chests, show it on hover and check/search in chests remotely.

This mod does most of that, but I consider remotely accessing chests cheating, so I'd love the option to only be able to **view** them.

Do you think this could be implementable? If yes, I'd be open to implementing it if you are open to contributions (I couldn't find contribution information for source code, only for translations).

**Comment by Pathoschild** [comment]
Hi! Sure, that feature could be useful for other players too and and it should be pretty straightforward. Pull requests are welcome if you want to take a look.

I'll close this ticket since I don't track suggestions as GitHub issues, but feel free to ping me (`@pathoschild`) in [#making-mods on the Stardew Valley Discord](https://smapi.io/community#Discord) if you want to discuss further!
