### ISSUE TITLE
[Automate] Add a new config for minimum items to keep

### ISSUE THREAD

**Issue by codewithbjim** [Pathoschild/LookupAnything#801]
It would be nice to have an option where the automate will skip processing materials if the materials has X number of items left in a chest

**Comment by Pathoschild** [comment]
Hi! You can [tell Automate not to remove the last item in a stack](https://github.com/Pathoschild/StardewMods/tree/develop/Automate#in-game-chest-settings), which also lets you set a minimum (e.g. two stacks of coal = minimum two coal in the chest).

I'll close this ticket since I don't track questions/suggestions on GitHub, but feel free to comment on [the Automate mod page](https://www.nexusmods.com/stardewvalley/mods/1063) if you have any other comments or questions!
