### ISSUE TITLE
[Base-Mod] Fairy Dust Automation

### ISSUE THREAD

**Issue by MoabMoam** [Pathoschild/LookupAnything#803]
While I was on my game, I was wondering how I aged my wines. Is it possible to add some commands to automate the use of Fairy Dust that are placed in chests?

**Comment by Pathoschild** [comment]
Not yet; supporting fairy dust would significantly affect performance due to the way chests & items work in the game code currently. Stardew Valley 1.6 has some changes to fix that though, so I'm planning to add support for fairy dust in the update for Stardew Valley 1.6.

I'll close this ticket since I don't track questions/suggestions on GitHub, but feel free to comment on [the Automate mod page](https://www.nexusmods.com/stardewvalley/mods/1063) if you have any other questions!
