### ISSUE TITLE
Lookup anything does not work in the mobile version of smapi

### ISSUE THREAD

**Issue by dmitriyromanyuk** [Pathoschild/LookupAnything#809]
Newtonsoft.Json.JsonReaderException: Can't parse JSON file.
Because of this, the mod is simply skipped.
I understand that this mod is not convenient to use on the phone, but I still wanted it to work.Pathoschild, can you fix this error, please?

Log: https://smapi.io/log/f7b6caac35c340afacf32102128614cd

**Comment by Pathoschild** [comment]
Hi! Can you come ask in [#modded-game-support on the Stardew Valley Discord](https://smapi.io/community#Discord) so we can run some tests? Feel free to ping me there with `@pathoschild`.

I'll close this though, since I only use GitHub issues for specific development tasks rather than support questions.
