### ISSUE TITLE
[AUTOMATE] Error processing machines when located in Mushroom Cave

### ISSUE THREAD

**Issue by alastir07** [Pathoschild/LookupAnything#856]
**Describe the bug**
When attempting to automate the mushroom cave on Stardew 1.6, an error occurs overnight as the mushrooms are generated. If there is a Dehydrator attached to the machine, the mushrooms disappear. If there is no Dehydrator, the errors still occur, but the mushrooms are correctly placed in the chest. Unsure if it's related to the farm type being the new Meadowlands farm or not.

**To Reproduce**
1. Configure Automate to use Wood Paths as a Connector
2. Load a save using the Meadowland farm that has progressed to have Demetrius install the mushroom boxes in the farm cave
3. Place paths between the mushroom boxes to lead them to a chest and the Dehydrator (as pictured)
4. Sleep
5. Observe the errors in the attached log file

**Log file**
https://smapi.io/log/865c61d131ae4291aceb3be941d5a1ed

**Screenshots**
![image](https://github.com/Pathoschild/StardewMods/assets/54958039/15a2ff94-c2d0-4ff2-9eee-982ed82160c5)

**Comment by n0proxy** [comment]
I'm having the same issue after updating to 2.0.2, can't remember if this happened with 2.0.1. Also using Meadowlands farm. Used crystal paths (set as a connector) to connect the mushroom boxes to a chest, avoiding the dehydrator.

EDIT: Actually I don't think I was seeing this in 2.0.1 as I don't recall seeing the SMAPI errors (I keep the window open on my second screen) the last morning I played before quitting (since I hooked up my mushroom cave yesterday, not just today). But there's a small chance I just didn't have the SMAPI window on top and got the errors that last day of playing 2.0.1 yesterday and just didn't see them. I did also add the Lookup Anything mod today.

**Comment by medicsteve09** [comment]
I am also having that same issue, even tried  just one chest placed in the middle of the first four boxes.  The same issue occurs, an in game error displays and the mushrooms are just gone.  The only other mods I am using aside from this one is UI Infosuite2, Lookup Anything, and Generic Mod Config Menu.

**Comment by alastir07** [comment]
This issue is resolved with version 2.0.3

**Comment by Udoachim** [comment]
For me the issue persists in 2.0.3

**Comment by Pathoschild** [comment]
@Udoachim If you still have the issue, can you [upload your SMAPI log](https://smapi.io/log) (see instructions on that page) and post the link here?
