### ISSUE TITLE
[Automate] "Avoid Removing Last Item in Stack" option is missing.

### ISSUE THREAD

**Issue by Measure76** [Pathoschild/LookupAnything#869]
**Describe the bug**
The "Avoid removing last item in stack" option is missing in the 1.6/2.0x update.

**To Reproduce**
1. Open Chest
2. Look for "Avoid removing last item in stack" option

Expected result: Option appears and is selectable

Actual result: Option does not appear and cannot be activated.

**Log file**
I do not think this is specific to my game as I have seen one other person indicating the issue on Nexus.

**Screenshots**
N/A

**Comment by Pathoschild** [comment]
Hi! That's a known limitation due to the way Automate works in Stardew Valley 1.6. It no longer reimplements the game's machine processing, it just calls the new machine code in 1.6. That means it's automatically compatible with custom-machine mods, but it can't easily change how the game processes input anymore.

I have an idea on how to fix that limitation, but it'll be a bit complicated so I'm focusing on compatibility fixes first. I'll close this since (a) there are multiple reports about the same underlying issue and (b) it's on my internal to-do list, but thanks for reporting it!
