### ISSUE TITLE
Automate does not combine stacks of items, causing it to halt prematurely

### ISSUE THREAD

**Issue by Deconkle** [Pathoschild/LookupAnything#930]
**Describe the bug**
Multiple stacks of materials will not combine within the same chest when that material is processed using Automate.

**To Reproduce**
1. Put 2 stacks of 999 wood in chest, fairy dust too.
2. Connect chest to Charcoal Kiln (multiple, in my case).
4. Upon completion you should see 2 separate stacks of 9 wood in the chest. Because kilns require 10 wood as input, neither stack is used.

**Log file**
[SMAPI Log](https://smapi.io/log/466d0b4c68c04bea973eec2146432748)

**Screenshots**
![image](https://github.com/Pathoschild/StardewMods/assets/24526230/c6242fbe-d663-4664-b12f-59b054ea40e9)

**Comment by Pathoschild** [comment]
Hi! That's a known limitation due to the way Automate works in Stardew Valley 1.6. It no longer reimplements the game's machine processing, it just calls the new machine code in 1.6. That means it's automatically compatible with custom-machine mods, but it can't easily change how the game processes input anymore.

I have an idea on how to fix that limitation, but it'll be a bit complicated so I'm focusing on compatibility fixes first. I'll close this since (a) there are multiple reports about the same underlying issue and (b) it's on my internal to-do list, but thanks for reporting it!
